name: Format (PHP)

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
          uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          extensions: curl, mbstring, pdo, bcmath, intl
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
          - uses: actions/cache@v1
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os}}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
          ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --no-suggest

      - name: Run cs-fixer
        run: |
          endor/bin/php-cs-fixer fix

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.LS_BUILDER_PA_GITHUB_TOKEN }}

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga:2.16.1.1

      - uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: Apply php-cs-fixer changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.LS_BUILDER_PA_GITHUB_TOKEN }}
